### ISSUE TITLE
Page.RSSLink is deprecated and will be removed in Hugo 0.93.0

### ISSUE THREAD

**Issue by svetlemodry** [EliiseS/AllinOne#2]
Seems like something we'd have to look into:

```
ERROR 2022/01/16 18:03:10 Page.RSSLink is deprecated and will be removed in Hugo 0.93.0. Use the Output Format's link, e.g. something like:
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}
ERROR 2022/01/16 18:03:10 Page.URL is deprecated and will be removed in Hugo 0.93.0. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
```
I did not have time to look into the code yet, but quick search gave me this link that seems relevant so far:

https://discourse.gohugo.io/t/page-hugo-is-deprecated-page-rsslink-is-deprecated/27037/2

https://gohugo.io/templates/rss/#the-embedded-rssxml

**Comment by EliiseS** [comment]
@svetlemodry I can't find any `page.RSSLink` or `Page.URL` in the theme. I also don't get this error when building hugo with `v0.92.0`, which is the latest release right now.

**Comment by svetlemodry** [comment]
Heh, yep you are right.
Looks like couple of my projects were using an old version of this template.
Sorry for the noise here! I guess this can be closed then.
Enjoy your weekend!
